feat: create periodic analyze and set default time format mongo (offsetDateTime)
match-mate/tags-management-service pull request #18
Opened 2024-05-22 04:07 UTC by FredyHG

2024-05-22 04:09 UTC, FredyHG commented
![image](https://github.com/match-mate/tags-management-service/assets/67878286/56c55714-bc72-4729-9b30-47072bd92271)
esta funcionando, porem não consegui testar, pois o fluxo está muito estranho para mim, se você conseguir me ajudar a testar ajudaria muito 🥺

2024-05-22 16:18 UTC, gabrieldasilvadev requested changes

2024-05-22 16:18 UTC, gabrieldasilvadev commented on build.gradle.kts
> +    //
?

2024-05-22 16:18 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/adapter/jobs/RequestTagJob.java
> +    @Scheduled(cron = "${app.cron}")
essa variavel esta no application.yml?
especifique o nome do cron.

`app:
  cron:
     <objetivo-do-cron>: "..."`

2024-05-22 16:18 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/adapter/persistence/TagAvailableStoragePortImpl.java
> +        System.out.println(savedDocumentList);
se quiser adicionar rastros do que esta sendo passado, utilize logs. nao use prints

2024-05-22 16:18 UTC, gabrieldasilvadev commented on src/main/resources/application.yml
> +  cron: 0 0 12 1,16 * ?
organizar melhor

2024-05-22 16:18 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/adapter/persistence/services/RequestTagService.java
> +        requestTagMongoRepository.save(tagDocument);
nome do metodo eh delete, mas chama um save? nao entendi

2024-05-22 16:18 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/adapter/persistence/services/RequestTagService.java
> +public class RequestTagService {
essa service nao faz sentido, ainda mais na camada de persistencia.

2024-05-22 16:18 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/adapter/jobs/RequestTagJob.java
> +public class RequestTagJob implements RequestTagPort {
Alterar nome dessa classe para que fiquei mais claro que eh um adaptador.
Sugestao de arquitetura, colocar o prefixo "Adapter", atualizar teste de arquitetura

2024-05-22 16:18 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/adapter/jobs/RequestTagJob.java
> +        List<RequestTagDocument> pendingTags = requestTagService.findAllPendingTagsWaitingForAnalysis(now.minusDays(7));
essa classe, eh um application sevice, ela pode conhecer o repository que abstrai o banco, ou ate mesmo trazer um repository concreto. mas, para no caso, esse "requestTagService" soh esta chamando outro metodo

2024-05-22 16:18 UTC, gabrieldasilvadev commented on src/test/java/com/matchmate/tagsmanagementservice/adapter/jobs/RequestTagJobTest.java
> +
?

2024-05-22 16:18 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/common/mappers/TagAvailableMapper.java
> +public class TagAvailableMapper {
criar teste

2024-05-22 16:18 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/common/mappers/TagRequestMapper.java
> +public class TagRequestMapper {
criar teste

2024-05-22 16:18 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/adapter/persistence/TagAvailableStoragePortImpl.java
> +public class TagAvailableStoragePortImpl implements TagAvailableStoragePort {
criar teste

2024-05-22 16:18 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/adapter/persistence/TagRequestStoragePortImpl.java
> +public class TagRequestStoragePortImpl implements TagRequestStoragePort {
criar teste

2024-05-22 16:21 UTC, gabrieldasilvadev commented
para testar esse feature, precisa preparar a massa no mongo

2024-05-22 17:34 UTC, FredyHG commented
![image](https://github.com/match-mate/tags-management-service/assets/67878286/f717e192-3934-43bd-8f3d-574b422b392c)
crie esse teste para o job, removi a service e fiz instanciando o repository no job e criei todos os testes que faltava

![image](https://github.com/match-mate/tags-management-service/assets/67878286/c0e47deb-d3ef-42a9-8871-c0c754b26119)
criei mais um arch test pra verificar se quem está dentro do pacote adapter.jobs deve conter o sufixo Adapter

2024-05-24 12:40 UTC, gabrieldasilvadev requested changes
adicionar logs

2024-05-24 12:40 UTC, gabrieldasilvadev commented on src/test/java/com/matchmate/tagsmanagementservice/adapter/jobs/RequestTagJobAdapterTest.java
> +        //WAITING CONFIG MONGO FOR CREATE TEST
teste unitario nao precisa configurar banco. o @Mock do Mockito, vc consegue mockar a chamado ao banco

2024-05-24 12:45 UTC, gabrieldasilvadev requested changes

2024-05-24 12:45 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/adapter/persistence/repository/RequestTagMongoRepository.java
> +    List<RequestTagDocument> findAllPendingTagsWaitingForAnalysis(OffsetDateTime dateRange);
trocar nome do metodo pra, findByDateBeforeAndRequestsGreaterThanEqual(), deixe o numero 20 parametrizavel em variavel de ambiente, tire o hard coded

2024-05-24 13:04 UTC, gabrieldasilvadev requested changes

2024-05-24 13:04 UTC, gabrieldasilvadev commented on src/archTest/java/AdapterRulesArchTest.java
> +    static final ArchRule classes_name_in_jobs_should_expected_Adapter_suffix =
pode dar rollback nesse teste. adicione um teste no ApplicationRulesArchTest, que todos as classes do package jobs, precisam ter o sufixo "Job"

2024-05-24 16:03 UTC, FredyHG commented on src/test/java/com/matchmate/tagsmanagementservice/adapter/jobs/RequestTagJobAdapterTest.java
> +        //WAITING CONFIG MONGO FOR CREATE TEST
é que vc disse preparar massa, oq seria esse "preparar massa"

2024-05-24 18:55 UTC, gabrieldasilvadev commented on src/test/java/com/matchmate/tagsmanagementservice/adapter/jobs/RequestTagJobAdapterTest.java
> +        //WAITING CONFIG MONGO FOR CREATE TEST
vc vai precisar preparar uma massa nos testes de integracao/e2e, onde precisamos dos componentes preparados para um determinado cenario. No caso, apenas precisamos mockar a chamada ao banco.

https://blog.onedaytesting.com.br/piramide-de-teses/

2024-05-24 18:57 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/adapter/jobs/RequestTagJobAdapter.java
> +        List<RequestTagDocument> pendingTags = requestTagMongoRepository.findAllPendingTagsWaitingForAnalysis(now.minusDays(7));
evitar o hard coded, parametrizar os 7 dias com env

2024-05-24 19:14 UTC, FredyHG commented on src/test/java/com/matchmate/tagsmanagementservice/adapter/jobs/RequestTagJobAdapterTest.java
> +        //WAITING CONFIG MONGO FOR CREATE TEST
A sim, pensei que você estava se referindo a esse método em específico

2024-05-25 00:56 UTC, gabrieldasilvadev requested changes

2024-05-25 00:56 UTC, gabrieldasilvadev commented on src/test/java/com/matchmate/tagsmanagementservice/adapter/jobs/RequestTagJobTest.java
> +    void analyzeRequestTags_ShouldProcessAndSaveTags() {
e se a lista estiver vazia?

2024-05-25 00:56 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/adapter/jobs/RequestTagJob.java
> +                .findByDateBeforeAndRequestsGreaterThanEqual(now.minusDays(7),Integer.valueOf(minimumRequest));
evitar hard coded, parametrizar os 7 dias em variavel de ambiente

2024-05-25 00:56 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/adapter/jobs/RequestTagJob.java
> +    @Value("${app.analyse-periodic-request-tags.minimum-request}")
criar properties para pegar a variavel. evitar usar @Value

2024-05-25 00:56 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/adapter/jobs/RequestTagJob.java
> +        log.info("Deleting pending request tags");
colocar no log quantidade de requests deletadas

2024-05-25 00:56 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/adapter/jobs/RequestTagJob.java
> +        log.info("Saving available tags");
adicionar no logs a quantidade de tags salvas

2024-05-25 00:56 UTC, gabrieldasilvadev commented on src/test/java/com/matchmate/tagsmanagementservice/adapter/jobs/RequestTagJobTest.java
> +        ReflectionTestUtils.setField(requestTagJob, "minimumRequest", "20");
qual a necessidade de injetar via reflection?

2024-05-25 18:32 UTC, gabrieldasilvadev requested changes

2024-05-25 18:32 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/adapter/jobs/RequestTagJob.java
>          log.info("Analyzing request tags");
Colocar nos logs a data que o job foi executado

2024-05-25 18:32 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/adapter/jobs/RequestTagJob.java
> +            throw new RuntimeException("No pending requests exist.");
Cria uma exception mais especifica. criar uma metrica que contabiliza quantas tags foram registradas

2024-05-25 18:32 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/adapter/jobs/RequestTagJob.java
>          log.info("Finished analyzing request tags");
Criar a metrica informada acima

2024-05-25 18:32 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/application/properties/DateRangeAnalyzeProperties.java
> +public class DateRangeAnalyzeProperties {
nao precisa criar uma property para cada atributo, ja que eles estao no mesmo contexto.

2024-05-25 18:32 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/application/properties/MinimumRequestProperties.java
> +public class MinimumRequestProperties {
nao precisa criar uma property para cada atributo, ja que eles estao no mesmo contexto.

2024-05-25 18:39 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/adapter/jobs/RequestTagJob.java
> +            throw new RuntimeException("No pending requests exist.");
https://www.baeldung.com/micrometer

2024-05-25 18:42 UTC, gabrieldasilvadev commented on src/main/java/com/matchmate/tagsmanagementservice/adapter/jobs/RequestTagJob.java
> +            throw new RuntimeException("No pending requests exist.");
https://prometheus.io/docs/practices/naming/

2024-05-25 19:25 UTC, gabrieldasilvadev approved these changes

2024-05-25 19:26 UTC, merged