Feature/kan 30 defini o de contrato para exposi o rest
match-mate/tags-management-service pull request #39
Opened 2024-06-05 01:42 UTC by FredyHG

2024-06-06 03:13 UTC, gabrieldasilvadev commented
pode colocar umas prints de como estao as classes pfvr

2024-06-06 03:14 UTC, gabrieldasilvadev requested changes

2024-06-06 03:14 UTC, gabrieldasilvadev commented on src/main/resources/static/api-docs.yaml
> +                  totalElements:
usar padrao snake_case

2024-06-06 03:20 UTC, FredyHG commented
Hj não fiz as alterações, tenho coisas pendentes aí, subi só pra vc dar um avaliada antes de eu subir a final

2024-06-06 04:19 UTC, gabrieldasilvadev requested changes

2024-06-06 04:19 UTC, gabrieldasilvadev commented on src/main/resources/static/api-docs.yaml
> +  /api/tags/request:
coloca /api/v1/tags

2024-06-06 11:29 UTC, gabrieldasilvadev requested changes

2024-06-06 11:29 UTC, gabrieldasilvadev commented on src/main/resources/static/api-docs.yaml
> +  /api/tags/request:
Seguir o padrão:
api/v1/request-tags


Motivo:
Já que estamos tratando o request-tag como um agregado, vamos deixá-lo com escopo próprio.

2024-06-06 13:21 UTC, FredyHG commented on src/main/resources/static/api-docs.yaml
> +                  totalElements:
![Screenshot from 2024-06-06 10-20-23](https://github.com/match-mate/tags-management-service/assets/67878286/fead2588-a204-468e-ac57-20e663182b64)

Esse é o padrão do pageable do spring, se mudar vamos ter que criar o pageable próprio

2024-06-06 21:31 UTC, gabrieldasilvadev commented on src/main/resources/static/api-docs.yaml
> +                  totalElements:
spring.jackson.property-naming-strategy=SNAKE_CASE

Nas configs

2024-06-07 18:07 UTC, gabrieldasilvadev commented
pode mandar print da classe como ficou pfvr

2024-06-07 18:10 UTC, FredyHG commented
> pode mandar print da classe como ficou pfvr

![image](https://github.com/match-mate/tags-management-service/assets/67878286/34669ee8-5788-43a6-8d0b-f02d226fe19d)

2024-06-07 18:59 UTC, gabrieldasilvadev commented
boaa

2024-06-07 18:59 UTC, gabrieldasilvadev approved these changes

2024-06-07 22:56 UTC, merged